name: Code Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
        id: go

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear mod cache
        run: go clean -modcache

      - name: Get dependencies
        run: |
          go mod tidy
          go mod vendor
          go get -v -t -d ./...

      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

  vet:
    name: go vet and statuscheck
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
        id: go

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear mod cache
        run: go clean -modcache

      - name: go vet
        run: |
          go mod tidy
          go mod vendor
          go get -v -t -d ./...
          go vet ./...

      - name: go staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1"
          install-go: false 